### PR TITLE
Add Mongo Seeding to Development tools section

### PR DESCRIPTION
**Pull request by pkosiec**
Hello,
I'm the author of Mongo Seeding - ultimate tool for populating MongoDB database. This is a project that I'm developing from a while ago (11.2017), but it's not popular - I haven't promoted it yet. There are some alternatives, but they are bare-bones - that's why I've started my own project.

I wasn't sure in which section I should put it - because this is not only Node.js library, but also CLI and Docker image.

Let me know what you think!

Best,
Pawel

### CODE REVIEW

**Comment by ramnes** [comment]
Hello @pkosiec! :wave: 

Thank you for the PR, and sorry for the very long time to answer.

What is the difference between Mongo Seeding and something like [MongoDB Smasher](https://github.com/duckie/mongo_smasher)? or just mongoimport?

**Comment by pkosiec** [comment]
Hi @ramnes! In both solutions you mentioned you need to define data in JSON files. In Mongo Seeding you can describe import data in JS files, which means you can execute some logic during db seeding. For example, you are able to randomize data in your own way, writing helper functions. Or, prepare production data import for initializing database. You can even use TypeScript for model validation - just to make sure the data structure is correct.

The data import can  be done with Docker Image (great for Docker compose setup), CLI, And programmatically with JS library.

**Comment by pkosiec** [comment]
Hi again @ramnes!
I've added a new section called "Motivation" to the main Readme of mongo-seeding, which explains why I've created such a tool. Hopefully it will clarify, why this tool is different than the others you mentioned 🙂 

https://github.com/pkosiec/mongo-seeding#motivation

**Comment by pkosiec** [comment]
You can do that with mongoose, but only programmatically. I've seen some libraries for that, but I didn't find any CLI or Docker image. Here you have a complete set of tools, ready to use, with the same API, which support JSON files from `mongoimport` as well.

Not everyone wants to use mongoose. For example, in TypeScript apps, when you utilize a very popular https://github.com/typeorm/typeorm library, you can reuse your data models (written in TS) for data import straight from the app. It enables type checking in your IDE, as well as during data import.

An example model from `typeorm` is as follows:
```javascript
import { Column as Property } from "typeorm";
import { ObjectId } from "mongodb";

export class Comment  {

  @Property()
  nickname: string;

  @Property()
  content: string;

  @Property()
  date: Date;

}
```
The class is used in your actual app, but it can be instantiated in your data import file. Then you have the type checking enabled and you won't make any mistake.

**Comment by ramnes** [comment]
Okay, let's do this. Thanks for your time and efforts, @pkosiec!

**Comment by pkosiec** [comment]
Thank you very much @ramnes!

**Pull request merged**
