### PR TITLE
Add VividCortex to the Monitoring section

### PR DESCRIPTION
**Pull request by xaprb**

### CODE REVIEW

**Comment by ramnes** [comment]
Hi @xaprb,

Could you move the link to the [Resources/More](https://github.com/ramnes/awesome-mongodb#more) section?

Thanks!

**Comment by xaprb** [comment]
Hi @ramnes, thanks, but I don't think that is the best place for it. VividCortex is directly comparable to Datadog, Percona Monitoring and Management, nagios plugins, etc. In fact, as I look at Resources/More I think I have a suggestion to improve it more broadly:

* let's break out a separate section for hosted-MongoDB providers, and put Atlas, ScaleGrid, mLab, Compose, ObjectRocket in the new section
* let's move MongoDB Cloud Manager to Tools/Administration

What do you think? I'm happy to do this in the PR (or create a separate PR if you'd like to avoid bundling these changes together).

**Comment by ramnes** [comment]
Sounds good, please do!

**Comment by xaprb** [comment]
Added a commit to implement what we discussed ^^^

**Comment by ramnes** [comment]
Nice, thank you!

**Pull request merged**
