### PR TITLE
adding DeriveJS to the list

### PR DESCRIPTION
**Pull request by yuval-a**
adding DeriveJS to the list...
thanks!

### CODE REVIEW

**Comment by ramnes** [comment]
Hi @yuval-a, that looks interesting, thanks! Can you please make the description simpler? i.e. one sentence, without bold text. :slightly_smiling_face:

**Comment by yuval-a** [comment]
How about:

> A reactive ODM that wraps native JavaScript data classes and objects with JavaScript proxies, enabling transparent DB persistence.

?

**Comment by ramnes** [comment]
> Reactive ODM that wraps native JavaScript objects to enable transparent DB persistence.

? :)

**Comment by yuval-a** [comment]
It's more important for me that 'Javascript Proxies' will be mentioned, so, let's settle on:

> Reactive ODM that uses Javascript Proxies to enable transparent DB persistence.

?

**Comment by ramnes** [comment]
That works too!

**Comment by ramnes** [comment]
Merged in #91

**Pull request closed without merging**
