### PR TITLE
Add Mingo.io desktop app

### PR DESCRIPTION
**Pull request by achtan**

### CODE REVIEW

**Comment by ramnes** [comment]
Hey @achtan, thanks for the MR!

It looks pretty good but I only have a Linux machine to test software with, sorry.

I'll close this for now but feel free to ping me here when you feel that you have more traction and users willing to vouch for your product, or if you have more than a website for me to look at.

**Comment by achtan** [comment]
hi, 
you can download and try linux version here: https://mingo.io/download/linux

let me know if there is any issue...

**Comment by ramnes** [comment]
You might want to add this link on your website. :wink: 

I played with it two minutes and had a few problems:
* it's impossible to remove an empty connection on the first creation form, and thus to validate the form
* only three or four columns were displayed when my 32" screen could print a lot more information
* it ended up crashing after a row update and had to kill the process

Also, what are Mingo's advantages (or planned ones) in comparison to other known desktop solutions, like Nosqlclient?

**Comment by achtan** [comment]
First of all, thx for merging!

We are updating our website and will add the link 🙂

also thanks for your feedback, let me address your points:

1. do you mean a connection or a project? I think you meant a project. We have a "context menu" (right-click) throughout the app and you can delete a project by right-click on it on left. But we'll try improve this usecase.

2. we will improve this, thanks.

3. since it's beta, we have dev-tools in the app, a screenshot of the console would help a lot.

Main advantages will be the user-interface, looks and the way Mingo presents data. We still have a long way to go...

**Comment by ramnes** [comment]
Hey @achtan,

I'm sorry but on reflection, I'll close this for now as Mingo seems to be at a too early development stage for entering this list.

Feel free to ping me here or to re-open a PR when you feel it's more stable and advanced! Good luck in your project.

**Comment by achtan** [comment]
Hi @ramnes, new version of Mingo is out.

Can you have a look at it, and let me know what you think... ?

web: https://mingo.io/

thx

**Pull request closed without merging**
